// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQNtL7At93a1JCqtvn0OoSYTbtbL-9KYs',
    appId: '1:642387324680:android:8aaea49716f8acc9f006bd',
    messagingSenderId: '642387324680',
    projectId: 'chat-8f49c',
    storageBucket: 'chat-8f49c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_UQPrtAMOQJhKxPI3gALCuENYan8vcYk',
    appId: '1:642387324680:ios:a400a48bd3f24db3f006bd',
    messagingSenderId: '642387324680',
    projectId: 'chat-8f49c',
    storageBucket: 'chat-8f49c.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_UQPrtAMOQJhKxPI3gALCuENYan8vcYk',
    appId: '1:642387324680:ios:a400a48bd3f24db3f006bd',
    messagingSenderId: '642387324680',
    projectId: 'chat-8f49c',
    storageBucket: 'chat-8f49c.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );
}
